ALTER TABLE invoices ADD COLUMN IF NOT EXISTS irpf_extra_percent NUMERIC(6,2);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS importe_autonomos NUMERIC(12,2);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS diezmo_percent NUMERIC(6,2);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS nomina_amount NUMERIC(12,2);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS ofrenda_sueldo NUMERIC(12,2);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS empresa_extras_amount NUMERIC(12,2);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS oficina_amount NUMERIC(12,2);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS gestor_amount NUMERIC(12,2);
