create table if not exists providers (
  supplier_code text primary key,
  name text not null,
  country text,
  tax_id text,
  manager_account_code text
);

-- Create table for expenses
create table if not exists expenses (
  entry_no bigint generated by default as identity primary key,
  supplier_code text,
  invoice_number text not null,
  invoice_date date not null,
  taxable_base numeric(12,2) not null default 0,
  vat_rate numeric(5,2) not null default 0,
  quarter smallint,
  created_at timestamptz default timezone('utc', now())
);

-- Optional index to speed up lookups by supplier code
create index if not exists idx_expenses_supplier_code on expenses (supplier_code);

